#!/usr/bin/env python3
"""Example of using volume mounts with smolvm."""

import asyncio
import os
import tempfile

from smolvm import Sandbox, SandboxConfig, MountSpec


async def main():
    # Create a temporary directory with some files
    with tempfile.TemporaryDirectory() as tmpdir:
        # Create test files
        test_file = os.path.join(tmpdir, "input.txt")
        with open(test_file, "w") as f:
            f.write("Hello from the host!\n")

        output_dir = os.path.join(tmpdir, "output")
        os.makedirs(output_dir)

        print(f"Host directory: {tmpdir}")
        print(f"Created input.txt with content: 'Hello from the host!'")
        print()

        # Create sandbox with mounts
        config = SandboxConfig(
            name="mount-example",
            mounts=[
                # Read-only mount for input
                MountSpec(source=tmpdir, target="/data", readonly=True),
                # Read-write mount for output
                MountSpec(source=output_dir, target="/output", readonly=False),
            ],
        )

        async with Sandbox(config) as sandbox:
            await sandbox.start()

            # Read from mounted volume
            print("=== Reading from mounted volume ===")
            result = await sandbox.exec(["cat", "/data/input.txt"])
            print(f"Content: {result.stdout}")

            # List mounted directory
            print("=== Listing mounted directory ===")
            result = await sandbox.exec(["ls", "-la", "/data"])
            print(result.stdout)

            # Write to output volume
            print("=== Writing to output volume ===")
            result = await sandbox.exec([
                "sh", "-c",
                "echo 'Generated by sandbox at $(date)' > /output/result.txt"
            ])

            # Verify write
            result = await sandbox.exec(["cat", "/output/result.txt"])
            print(f"Written content: {result.stdout}")

        # Verify file exists on host
        output_file = os.path.join(output_dir, "result.txt")
        if os.path.exists(output_file):
            with open(output_file) as f:
                print(f"=== Host sees the file ===")
                print(f"Content on host: {f.read()}")


if __name__ == "__main__":
    asyncio.run(main())
